# Generated by Django 6.0.3 on 2026-03-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ledger', '0002_product_reorder_level_alter_product_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_document',
            field=models.CharField(blank=True, help_text='PO Number, Invoice ID, or Receipt Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
    ]
