# Generated by Django 6.0.3 on 2026-03-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ledger', '0003_product_description_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='remarks',
            field=models.TextField(blank=True, help_text='Reason for adjustment or general notes', null=True),
        ),
    ]
