# Generated by Django 6.0.3 on 2026-03-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ledger', '0004_stockmovement_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='reference_document',
        ),
        migrations.AddField(
            model_name='location',
            name='short_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='contact',
            field=models.CharField(blank=True, help_text='Vendor or Customer name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='short_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
