# Generated by Django 5.0.3 on 2026-03-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_ledger", "0007_alter_location_id_alter_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("READY", "Ready"),
                    ("PACKED", "Packed"),
                    ("DONE", "Done"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DONE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
