# Generated by Django 6.0.3 on 2026-03-14 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # CreateModel operations for Location, Product, StockLedger removed.
        # These models were moved to the stock_ledger app.
        # Migration already applied to DB — safe to leave empty.
    ]

