# Generated by Django 5.0.3 on 2026-03-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        # AlterField operations for location, product, stockledger removed.
        # These models were moved to the stock_ledger app.
        # Migration already applied to DB — safe to leave empty.
    ]

