<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-03-14 10:38
=======
# Generated by Django 5.0.3 on 2026-03-14 10:29
>>>>>>> 7f21110 (Final Updated Core Inventory)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockledger',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='performed_by',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='StockLedger',
        ),
    ]
