<<<<<<< HEAD
# Generated by Django 5.0.3 on 2026-03-14 10:29

from django.db import migrations
=======
# Generated by Django 6.0.3 on 2026-03-14 10:38

from django.db import migrations, models
>>>>>>> 81ef4baaff35d9fe16ea7ec1e8fc350e822394c3


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("identity", "0003_passwordresetotp"),
=======
        ('identity', '0003_passwordresetotp'),
>>>>>>> 81ef4baaff35d9fe16ea7ec1e8fc350e822394c3
    ]

    operations = [
        migrations.RemoveField(
<<<<<<< HEAD
            model_name="stockledger",
            name="source_location",
        ),
        migrations.RemoveField(
            model_name="stockledger",
            name="destination_location",
        ),
        migrations.RemoveField(
            model_name="stockledger",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stockledger",
            name="performed_by",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="StockLedger",
=======
            model_name='stockledger',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='performed_by',
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='StockLedger',
>>>>>>> 81ef4baaff35d9fe16ea7ec1e8fc350e822394c3
        ),
    ]
