# Generated by Django 5.0.3 on 2026-03-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_passwordresetotp'),
    ]

    operations = [
        # Operations removed — these models (StockLedger, Location, Product)
        # were moved to the stock_ledger app. The duplicate 0004 migrations
        # caused a KeyError during state replay. Since already applied to DB,
        # this is safe to leave empty.
    ]
