# Generated by Django 6.0.3 on 2026-03-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_remove_stockledger_destination_location_and_more'),
        ('identity', '0004_remove_stockledger_source_location_and_more'),
    ]

    operations = [
    ]
