# Generated by Django 6.0.3 on 2026-03-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_merge_20260314_1747'),
        ('identity', '0005_profile'),
    ]

    operations = [
    ]
